### ISSUE TITLE
Aarch64 support?

### ISSUE THREAD

**Issue by danielnorberg** [toolfactory/narcissus#10]
Are there any plans for native aarch64 (linux arm, macbook m1) support?

**Comment by lukehutch** [comment]
Hi, I would love to support Aarch64, but we would need Github Actions support for building for that architecture first. Maybe a cross-compiler could be set up to accomplish this, but honestly I have extremely limited time to work on this right now. Would you be willing to take a shot at this, by chance?

**Comment by Roberto-Gentili** [comment]
I found a way to compile for aarch64 and that can be replicated for other architectures. It consists:
* [to add a condition in the workflow](https://github.com/burningwave/jvm-driver/blob/5e55c207040e8e9ead320f95aee7b7f044ca5b80/.github/workflows/%5BA%5D%20build%20and%20test%2C%20release%20if%20requested.yml#L73)
* [to add a new profile in the pom.xml](https://github.com/burningwave/jvm-driver/blob/5e55c207040e8e9ead320f95aee7b7f044ca5b80/native/pom.xml#L83)
This would leave out only the library load test.
Maybe when you have time you can replicate it on Narcissus and for all architectures on linux for which a cross compiler is available.

**Comment by Roberto-Gentili** [comment]
I found a way to compile for aarch64 and that can be replicated for other architectures for which a cross compiler is available on Linux. It consists:
* [to add a condition in the workflow](https://github.com/burningwave/jvm-driver/blob/5e55c207040e8e9ead320f95aee7b7f044ca5b80/.github/workflows/%5BA%5D%20build%20and%20test%2C%20release%20if%20requested.yml#L73)
* [to add a new profile in the pom.xml](https://github.com/burningwave/jvm-driver/blob/5e55c207040e8e9ead320f95aee7b7f044ca5b80/native/pom.xml#L83)

<br/>

This would leave out only the library load test.
**Maybe when you have time you can replicate it on Narcissus and for all architectures on Linux for which a cross compiler is available**.

**Comment by michael-simons** [comment]
Hej. All the familiar faces :) 

AFAIK GitHub does only support Arm64 on Mac these days. 

I can't help with the JVM-Driver, but the profile in the pom is there.

**Comment by lukehutch** [comment]
@michael-simons do you have users blocked on this on Windows-Aarch64, or something? I don't understand your comment. 

Narcissus is the most egregious hack of the JVM of all time, with the exception of JVM-Driver, which would not have been possible without the genius of @Roberto-Gentili -- so I hope there isn't much mission-critical use of either of them!

**Comment by lukehutch** [comment]
Fixed on MacOS via #15 -- not currently fixable for Windows-aarch64, because GitHub doesn't support that build.

**Comment by michael-simons** [comment]
No, no critical users on Windows. I probably misinterpreted the GitHub profile, actually. Only wanted to work on MacOS, so that I can be sure my ClassGraph PRs build green :)

**Comment by Roberto-Gentili** [comment]
> No, no critical users on Windows. I probably misinterpreted the GitHub profile, actually. Only wanted to work on MacOS, so that I can be sure my ClassGraph PRs build green :)

... Also take a look at [Burningwave\JVM-Driver](https://github.com/burningwave/jvm-driver) which is a version of JVM-Driver that uses a [smaller but very fast](https://github.com/burningwave/jvm-driver/issues/3#issuecomment-1149840706) native engine

**Comment by Roberto-Gentili** [comment]
> Narcissus is the most egregious hack of the JVM of all time, with the exception of JVM-Driver, which would not have been possible without the genius of @Roberto-Gentili -- so I hope there isn't much mission-critical use of either of them!

Thanks, but the real genius here is you reading your CV on LinkedIn :-)
