### ISSUE TITLE
Enable pipeline

### ISSUE THREAD

**Issue by jabrena** [toolfactory/narcissus#14]
It could be healthy to have a pipeline enabled for the repository. 

What do you think?

**Comment by lukehutch** [comment]
A pipeline?

**Comment by jabrena** [comment]
Github Actions

**Comment by lukehutch** [comment]
Oh, OK. Then this is the same as #10.

Truth be told, I haven't modified or built this in close to 2 years... As far as I know the code is feature-complete and bug-free. The only thing that needs to be done is to add more architectures through cross-compilation in GitHub Actions, but there's not much demand for that right now.

**Comment by lukehutch** [comment]
Right, I never set it up, I always just built manually and pushed the artifacts out to Maven.

We don't need a pipeline if we have nothing to build. The code is feature-complete and appears to be completely bug-free. And honestly I have close to zero time to work on this right now.

If there were a lot of demand for AArch64, maybe that would inspire me to do it. But first I would want to see a PR from somebody supporting local cross-compilation to AArch64 via Maven. If you are willing to get that working, I'll merge your PR.

**Comment by lukehutch** [comment]
This is set up to build with GitHub Actions now.
